DROP TABLE IF EXISTS LOCOMOTIVES;
CREATE TABLE LOCOMOTIVES(ID INT PRIMARY KEY,
   NAME VARCHAR(255));
INSERT INTO LOCOMOTIVES VALUES(1, 'LOCOMOTIVE NAME ONE');
INSERT INTO LOCOMOTIVES VALUES(2, 'LOCOMOTIVE NAME TWO');